services:
  alquimistas-atomicos:
    build: .
    env_file:
      - config.env
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=${PORT}
    ports:
      - "18020:${PORT:-8080}"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
